stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean install -Dmaven.test.skip=true"
  artifacts:
    paths:
      - target/*.jar

# deploy-heroku:
#  stage: deploy
#  image: ruby:2.6
#  before_script:
#     - gem install dpl --version 1.10.15
#     - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
#  script:
#     - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
#     - export HEROKU_API_KEY=$HEROKU_API_KEY
#     - heroku run --app $HEROKU_APP_NAME migrate
#  environment:
#     name: production
#     url: $HEROKU_APP_HOST
#  only:
#     - production

# deploy-heroku-staging:
#  stage: deploy
#  image: ruby:2.6
#  before_script:
#     - gem install dpl --version 1.10.15
#     - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
#  script:
#     - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY
#     - export HEROKU_API_KEY=$HEROKU_API_KEY
#     - heroku run --app $HEROKU_APP_NAME_STAGING migrate
#  environment:
#     name: production
#     url: $HEROKU_APP_HOST_STAGING
#  only:
#     - main