stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
#  script: "mvn clean install -Dmaven.test.skip=true"
  script: "mvn -T 1C clean install -Dmaven.test.skip -DskipTests"
  artifacts:
    paths:
      - target/*.jar

deploy-heroku-production:
  stage: deploy
  image: ruby:2.6
  before_script:
     - gem install dpl --version 1.10.15
     - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
     - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
#     - export HEROKU_API_KEY=$HEROKU_API_KEY
#     - heroku run --app $HEROKU_APP_NAME migrate
  environment:
     name: production
     url: https://$HEROKU_APP_PRODUCTION.herokuapp.com
  only:
     - master

deploy-heroku-staging:
  stage: deploy
  image: ruby:2.6
  before_script:
     - gem install dpl --version 1.10.15
     - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
     - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#     - export HEROKU_API_KEY=$HEROKU_API_KEY
#     - heroku run --app $HEROKU_APP_NAME_STAGING migrate
  environment:
     name: staging
     url: https://$HEROKU_APP_STAGING.herokuapp.com
  only:
     - staging