spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
#server:
#  cors:
#    origins:
#      - http://localhost:8081
#      - https://propensi-a03-staging.herokuapp.com:8081
#      - https://propensi-a03.herokuapp.com:8081