# Generated by Django 4.0.3 on 2022-03-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaryaIlmiah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500)),
                ('judul', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('jenis', models.CharField(max_length=500)),
                ('abstrak', models.CharField(max_length=5000)),
                ('tglVerifikasi', models.DateField()),
                ('daftarPengunduh', models.ManyToManyField(to='propensi.profile')),
                ('dosenPembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_pembimbing', to='propensi.profile')),
                ('userPengunggah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_penunggah', to='propensi.profile')),
                ('verifikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifikator', to='propensi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=500)),
                ('tglDibuat', models.DateField()),
                ('tglDisunting', models.DateField()),
                ('isiPengumuman', models.CharField(max_length=5000)),
                ('stafPembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propensi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('listKaryaIlmiah', models.ManyToManyField(to='propensi.karyailmiah')),
            ],
        ),
    ]
