# Generated by Django 4.0.3 on 2022-03-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyailmiah',
            old_name='kataKunci',
            new_name='keyword',
        ),
    ]
