# Generated by Django 4.0.3 on 2022-03-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0002_karyailmiah_pengumuman_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='dosenPembimbing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dosen_pembimbing', to='propensi.profile'),
        ),
        migrations.AlterField(
            model_name='karyailmiah',
            name='userPengunggah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_penunggah', to='propensi.profile'),
        ),
        migrations.AlterField(
            model_name='karyailmiah',
            name='verifikator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verifikator', to='propensi.profile'),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='stafPembuat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='propensi.profile'),
        ),
    ]
