# Generated by Django 4.0.3 on 2022-03-22 11:24

from django.db import migrations, models
import propensi.models


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0003_profile_full_name_alter_karyailmiah_userpengunggah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='filePDF',
            field=models.FileField(max_length=500, null=True, upload_to=propensi.models.KaryaIlmiah.get_upload_path),
        ),
    ]
