# Generated by Django 4.0.3 on 2022-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0003_rename_keyword_karyailmiah_katakunci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('tanggalKunjungan', models.DateField()),
            ],
        ),
    ]
