# Generated by Django 4.0.3 on 2022-03-23 03:46

from django.db import migrations, models
import propensi.models


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0006_alter_karyailmiah_filepdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='filePDF',
            field=models.FileField(max_length=500, null=True, upload_to=propensi.models.KaryaIlmiah.get_upload_path, validators=[propensi.models.KaryaIlmiah.validate_file_extension]),
        ),
    ]
