# Generated by Django 4.0.3 on 2022-03-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0006_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='nama'),
        ),
    ]
