# Generated by Django 4.0.3 on 2022-03-23 03:50

import django.core.validators
from django.db import migrations, models
import propensi.models


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0007_alter_karyailmiah_filepdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='filePDF',
            field=models.FileField(max_length=500, null=True, upload_to=propensi.models.KaryaIlmiah.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
