# Generated by Django 4.0.3 on 2022-03-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0007_profile_full_name'),
        ('propensi', '0008_alter_karyailmiah_filepdf'),
    ]

    operations = [
    ]
