# Generated by Django 4.0.3 on 2022-04-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0009_merge_20220323_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyailmiah',
            name='kataKunci',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='karyailmiah',
            name='dosenPembimbing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dosen_pembimbing', to='propensi.profile'),
        ),
    ]
