# Generated by Django 4.0.3 on 2022-04-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0010_karyailmiah_katakunci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyailmiah',
            name='daftarPengunduh',
        ),
        migrations.CreateModel(
            name='DaftarUnduhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProfile', models.CharField(max_length=500)),
                ('fullName', models.CharField(max_length=500)),
                ('tglUnduh', models.CharField(max_length=500)),
                ('karyaIlmiah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propensi.karyailmiah')),
            ],
        ),
    ]
