# Generated by Django 4.0.3 on 2022-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propensi', '0012_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyailmiah',
            name='userPenandaBuku',
            field=models.ManyToManyField(to='propensi.profile'),
        ),
    ]
